import { AnimatePresence, motion } from "framer-motion";
import { ArrowDown, ArrowUp, ChevronDown, ChevronUp, Eye, Trash2 } from "lucide-react";
import { Button } from "../ui/button";
import { cn } from "@/lib/utils";
import { HighlightSettingsForm } from "./HighlightSettingsForm";
import type { Highlight } from "@/types";

export function HighlightRow({ highlight, index, total, snippet, isExpanded, isPreviewing, dragHandle, onToggleExpand, onMove, onPreview, onDelete, onUpdate }: { highlight: Highlight; index: number; total: number; snippet?: string; isExpanded: boolean; isPreviewing: boolean; dragHandle: React.ReactNode; onToggleExpand: (id: string) => void; onMove: (id: string, direction: -1 | 1) => void; onPreview: (index: number) => void; onDelete: (id: string) => void; onUpdate: (id: string, patch: Partial<Highlight>) => void }) {
  const text = snippet === undefined ? "…" : snippet.replace(/\s+/g, " ").trim() || "(empty selection)";
  return <div className={cn("rounded-md border transition-colors", isPreviewing ? "border-primary/60 bg-primary/10" : isExpanded ? "border-primary/40 bg-card/80" : "border-border/40 bg-card/40 hover:bg-card/60")}><div className="flex items-center gap-1 px-2 py-1">{dragHandle}<button type="button" className="flex min-w-0 flex-1 items-center gap-1.5 text-left" onClick={() => onToggleExpand(highlight.id)} title={`L${highlight.startLine + 1}:${highlight.startChar} → L${highlight.endLine + 1}:${highlight.endChar}`}><span className="shrink-0 font-mono text-[10px] text-primary/80">#{index + 1}</span><span className="truncate font-mono text-[10px] text-foreground/80">{text}</span></button><Button variant="ghost" size="icon" className="h-5 w-5 shrink-0" disabled={index === 0} onClick={() => onMove(highlight.id, -1)}><ArrowUp className="h-3 w-3" /></Button><Button variant="ghost" size="icon" className="h-5 w-5 shrink-0" disabled={index === total - 1} onClick={() => onMove(highlight.id, 1)}><ArrowDown className="h-3 w-3" /></Button><Button variant="ghost" size="icon" className={cn("h-5 w-5 shrink-0", isPreviewing && "bg-primary/20 text-primary")} onClick={() => onPreview(index)}><Eye className="h-3 w-3" /></Button><Button variant="ghost" size="icon" className="h-5 w-5 shrink-0" onClick={() => onToggleExpand(highlight.id)}>{isExpanded ? <ChevronUp className="h-3 w-3" /> : <ChevronDown className="h-3 w-3" />}</Button><Button variant="ghost" size="icon" className="h-5 w-5 shrink-0 hover:text-destructive" onClick={() => onDelete(highlight.id)}><Trash2 className="h-3 w-3" /></Button></div><AnimatePresence>{isExpanded && <motion.div className="px-2 pb-2" initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }} transition={{ duration: 0.15 }}><HighlightSettingsForm highlight={highlight} onUpdate={onUpdate} /></motion.div>}</AnimatePresence></div>;
}
