import { memo } from "react";
import { ArrowRight, Check, Copy, Download, FileCode, Pencil, Trash2, X } from "lucide-react";
import { Button } from "../ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "../ui/card";
import { Input } from "../ui/input";
import { formatRelative } from "@/lib/utils";
import { useSlideThumbnail } from "@/hooks/useSlideThumbnail";
import { themeBackground, type ProjectSummary } from "@/types";

function ProjectThumb({ project }: { project: ProjectSummary }) {
  const thumb = useSlideThumbnail({ slideId: project.firstSlideId || project.id, code: project.firstSlideCode, theme: project.theme, language: project.language, initialHtml: project.firstSlideThumbnail || undefined });
  return <div ref={thumb.ref} className="flex h-9 w-9 shrink-0 items-center justify-center overflow-hidden rounded-lg border border-border/60" style={{ backgroundColor: themeBackground(project.theme) }} aria-hidden="true">{thumb.html ? <code className="pointer-events-none block font-mono" style={{ fontSize: "3.5px", lineHeight: 1.3, whiteSpace: "pre" }} dangerouslySetInnerHTML={{ __html: thumb.html }} /> : <FileCode className="h-4 w-4 text-primary" />}</div>;
}

export const ProjectCard = memo(function ProjectCard({ project, isRenaming, renameValue, onRenameValueChange, onCommitRename, onCancelRename, onStartRename, onOpen, onDuplicate, onExport, onDelete, duplicateBusy, commitBusy }: { project: ProjectSummary; isRenaming: boolean; renameValue: string; onRenameValueChange: (value: string) => void; onCommitRename: () => void; onCancelRename: () => void; onStartRename: (id: string, name: string) => void; onOpen: (id: string) => void; onDuplicate: (id: string) => void; onExport: (id: string) => void; onDelete: (id: string, name: string) => void; duplicateBusy: boolean; commitBusy: boolean }) {
  return <Card className="group cursor-pointer transition-all duration-200 hover:-translate-y-0.5 hover:border-primary/50 hover:shadow-lg" onClick={() => { if (!isRenaming) onOpen(project.id); }}><CardHeader className="pb-3"><div className="flex items-start justify-between gap-2"><div className="flex min-w-0 flex-1 items-center gap-2.5"><ProjectThumb project={project} /><div className="min-w-0 flex-1">{isRenaming ? <div className="flex items-center gap-1" onClick={(e) => e.stopPropagation()}><Input autoFocus value={renameValue} onChange={(e) => onRenameValueChange(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") void onCommitRename(); if (e.key === "Escape") onCancelRename(); }} className="h-8 text-sm" /><Button variant="ghost" size="icon" className="h-8 w-8 shrink-0" onClick={() => void onCommitRename()} disabled={commitBusy}><Check className="h-4 w-4 text-emerald-500" /></Button><Button variant="ghost" size="icon" className="h-8 w-8 shrink-0" onClick={onCancelRename}><X className="h-4 w-4" /></Button></div> : <><CardTitle className="truncate text-base font-semibold">{project.name}</CardTitle><CardDescription className="text-xs">{project.slideCount} slide{project.slideCount !== 1 ? "s" : ""}</CardDescription></>}</div></div>{!isRenaming && <div className="flex shrink-0 gap-1 opacity-0 transition-opacity group-hover:opacity-100"><Button variant="ghost" size="icon" className="h-8 w-8" title="Rename" onClick={(e) => { e.stopPropagation(); onStartRename(project.id, project.name); }}><Pencil className="h-3.5 w-3.5" /></Button><Button variant="ghost" size="icon" className="h-8 w-8" title="Duplicate project" onClick={(e) => { e.stopPropagation(); onDuplicate(project.id); }} disabled={duplicateBusy}><Copy className="h-4 w-4" /></Button><Button variant="ghost" size="icon" className="h-8 w-8" title="Export JSON" onClick={(e) => { e.stopPropagation(); onExport(project.id); }}><Download className="h-4 w-4" /></Button><Button variant="ghost" size="icon" className="h-8 w-8 hover:bg-destructive/10 hover:text-destructive" onClick={(e) => { e.stopPropagation(); onDelete(project.id, project.name); }}><Trash2 className="h-4 w-4" /></Button></div>}</div></CardHeader><CardContent className="pb-3"><span className="rounded-md bg-muted px-2 py-1 text-xs font-medium text-foreground/70">{project.theme}</span></CardContent><CardFooter className="flex items-center justify-between pt-0"><span className="text-xs text-muted-foreground">Updated {formatRelative(project.updatedAt)}</span><ArrowRight className="h-4 w-4 text-muted-foreground transition-transform group-hover:translate-x-1" /></CardFooter></Card>;
});
